#!/bin/bash

git diff --diff-filter=d --staged --name-only | grep -e '\(.*\).swift$' | while read line; do
    swift-format format -i "${line}" --configuration swift-format-config.json;
    git add "$line";
done

git diff --diff-filter=d --staged --name-only | grep -e '\(.*\).swift$' | while read line; do
    swift-format lint -s "${line}" --configuration swift-format-config.json || exit 1;
done