# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new version to Firebase"
  lane :deploy do
    ensure_git_status_clean
    latest_release = firebase_app_distribution_get_latest_release(
      app: "1:524233830532:android:39cfce23934bb9fecc52d1",
      service_credentials_file: 'firebase-admin.json'
    )
    increment_version_code({ version_code: latest_release[:buildVersion].to_i + 1 })
    gradle(task: "assembleRelease")
    firebase_app_distribution(
        app: "1:524233830532:android:39cfce23934bb9fecc52d1",
        service_credentials_file: 'firebase-admin.json',
        groups: 'membrane-testers'
    )
    reset_git_repo(skip_clean: true)
  end
end
