export { default as BulbIcon } from './Bulb.svg';
export { default as CameraIcon } from './Cam.svg';
export { default as CameraDisabledIcon } from './Cam disabled.svg';
export { default as CheckIcon } from './Check.svg';
export { default as CloseIcon } from './Close.svg';
export { default as CopyIcon } from './Copy.svg';
export { default as ErrorIcon } from './Error.svg';
export { default as ExternalLinkIcon } from './External link.svg';
export { default as FilterIcon } from './Filter.svg';
export { default as ForwardIcon } from './Forward.svg';
export { default as FlipCameraIcon } from './outline-refresh.svg';
export { default as HangupIcon } from './Hangup.svg';
export { default as HeadphonesIcon } from './Headphones.svg';
export { default as HomeIcon } from './Home.svg';
export { default as ImageIcon } from './Image.svg';
export { default as InfoIcon } from './Info.svg';
export { default as ListrightIcon } from './Listright.svg';
export { default as MenuVerticalIcon } from './Menu vertical.svg';
export { default as Message1Icon } from './Message-1.svg';
export { default as MessageIcon } from './Message.svg';
export { default as MicrophoneDisabledIcon } from './Microphone-off.svg';
export { default as MicrophoneIcon } from './Microphone.svg';
export { default as MoonIcon } from './Moon.svg';
export { default as MusicIcon } from './Music.svg';
export { default as PastIcon } from './Past.svg';
export { default as PauseIcon } from './Pause.svg';
export { default as PhoneCrossIcon } from './Phone cross.svg';
export { default as PinIcon } from './Pin.svg';
export { default as PlusIcon } from './Plus.svg';
export { default as QuotesIcon } from './Quotes.svg';
export { default as RewindIcon } from './Rewind.svg';
export { default as RotateRightIcon } from './Rotate right.svg';
export { default as SadIcon } from './Sad.svg';
export { default as ScreenIcon } from './Screen.svg';
export { default as ScreenshareIcon } from './Screenshare.svg';
export { default as ScreenshareDisabledIcon } from './Screen-off.svg';
export { default as SearchIcon } from './Search.svg';
export { default as SendIcon } from './Send.svg';
export { default as ServerIcon } from './Server.svg';
export { default as SettingsIcon } from './Settings.svg';
export { default as SortIcon } from './Sort.svg';
export { default as SoundBigIcon } from './Sound big.svg';
export { default as SoundIcon } from './Sound.svg';
export { default as SpeakerIcon } from './Speaker.svg';
export { default as StarIcon } from './Star.svg';
export { default as SunIcon } from './Sun.svg';
export { default as TickIcon } from './Tick.svg';
export { default as ToBeReplacedIcon } from './To be replaced.svg';
export { default as TrashIcon } from './trash.svg';
export { default as UserIcon } from './User.svg';
export { default as WindowsIcon } from './Windows.svg';
