name: Unit tests
on:
  pull_request:
jobs:
  check:
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install node dependencies
        run: yarn && cd example && yarn
      - name: Run unit tests
        run: yarn test
