name: Unit tests
on:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18.12.0
          cache: 'yarn'
      - name: Install node dependencies
        run: yarn && cd example && yarn
      - name: Run unit tests for the library
        run: yarn test -- src/__tests__/index.test.tsx
      - name: Run unit tests for the example app
        run: cd example && yarn test
